### ISSUE TITLE
Meta tag for the responsive pages

### ISSUE THREAD

**Issue by marekxhtml** [xhtmlized/generator-xh#139]
I think that meta tag for the responsive pages should be automatically added.

**Comment by piotrkulpinski** [comment]
Marek, we've discussed that internally already and agreed, that it could create confusion when non-responsive pages would break and it wouldn't be obvious that it's caused by the meta viewport tags.

I think we can add a commented line which you can either uncomment or remove depending on your project needs.

Let's wait to hear what others think.

**Comment by thymikee** [comment]
Actually, the commented out meta viewport is added in the newest release of generator -- [head.html](https://github.com/xhtmlized/generator-xh/blob/master/app/templates/src/includes/_head.html)

**Comment by piotrkulpinski** [comment]
![meme](http://s2.quickmeme.com/img/d5/d5924c4c74859898f56139faf37c859ce3cf80e0d55055147a5bc156371c2085.jpg)
